server.port=${AUTH_SERVICE_PORT}

# ================= DATABASE =================
spring.datasource.url=${AUTH_DB_URL}
spring.datasource.username=${AUTH_DB_USERNAME}
spring.datasource.password=${AUTH_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ================= MAIL =================
spring.mail.host=${AUTH_MAIL_HOST}
spring.mail.port=${AUTH_MAIL_PORT}
spring.mail.username=${AUTH_MAIL_USERNAME}
spring.mail.password=${AUTH_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================= JWT =================
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}

# ================= APP =================
app.frontend-url=${FRONTEND_URL}
app.otp.ttl-minutes=10

# ================= GOOGLE LOGIN =================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${AUTH_GOOGLE_REDIRECT_URI}

# ================= FACEBOOK LOGIN =================
spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET}
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri=${AUTH_FACEBOOK_REDIRECT_URI}

spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v18.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v18.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email,picture
spring.security.oauth2.client.provider.facebook.user-name-attribute=id